# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "blog"
description: > # this means to ignore newlines until "email:"
   more mindless musings

email: gabriel@pascualy.org
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Gabriel Pascualy'
author: 'Gabriel Pascualy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https//travel.pascualy.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@gpascualy'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://linkedin.com/in/gabrielpascualy
    desc: Connect with me on LinkeIn
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
